### ISSUE TITLE
iris.py: FileNotFoundError: [Errno 2] No such file or directory: 'Xyce'

### ISSUE THREAD

**Issue by cyber-g** [mawatfa/ebana#4]
After applying fix from PR https://github.com/mawatfa/ebana/pull/3
the execution of `iris.py` fails and throws :

```
Unsupported Ngspice version 36
Unsupported Ngspice version 36
Unsupported Ngspice version 36
Unsupported Ngspice version 36
Unsupported Ngspice version 36
Unsupported Ngspice version 36
Unsupported Ngspice version 36
Unsupported Ngspice version 36
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "path/ebana-cyber-g/src/equiprop.py", line 89, in train
    self.free_phase(X, idx)
  File "path/ebana-cyber-g/src/equiprop.py", line 27, in free_phase
    self.spice.simulate_circuit()
  File "path/ebana-cyber-g/src/spicesimulation.py", line 66, in simulate_circuit
    self.analysis = simulator.operating_point()
  File "path/ebana-venv/lib/python3.10/site-packages/PySpice/Spice/Simulation.py", line 1194, in operating_point
    return self._run('operating_point', *args, **kwargs)
  File "path/ebana-venv/lib/python3.10/site-packages/PySpice/Spice/Xyce/Simulation.py", line 66, in _run
    raw_file = self._xyce_server(spice_input=str(self))
  File "path/ebana-venv/lib/python3.10/site-packages/PySpice/Spice/Xyce/Server.py", line 123, in __call__
    process = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xyce'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "path/ebana-cyber-g/test_circuits/iris.py", line 203, in <module>
    model.fit(
  File "path/ebana-cyber-g/src/analognn.py", line 123, in fit
    results = pool.starmap(EqProp(self).train, child_processes_args)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'Xyce'
```

The problem is related to the `__init__` method in : [spicesimulation.py](https://github.com/mawatfa/ebana/blob/main/src/spicesimulation.py)
([spicesimulation.py#L27](https://github.com/mawatfa/ebana/blob/main/src/spicesimulation.py#L27))

Looking in detail, we can see that the first 8 instances of `EqProp(self).train` produced by `pool.starmap()` in [analognn.py](https://github.com/mawatfa/ebana/blob/main/src/analognn.py) initialize and run properly. 

However, the second round fails because, for unknown reason to me (I guess there is a kind of reuse of previous objects), the attribute `model.simulator` now exists and is set to `ngspice`. 

In this case, the code makes a nonsensical action : it overwrites the attribute with : `model.simulator = 'xyce'`
([spicesimulation.py#L32C13-L32C37](https://github.com/mawatfa/ebana/blob/30600c4173d02bab909f42cd2e5ffcb1dfe87e3e/src/spicesimulation.py#L32C13-L32C37))

On my computer, Xyce is not available, hence the failure. 

**The expected behavior is** : when the simulator attribute is set, it should be kept unmodified.

**Comment by medwatt** [comment]
@cyber-g, thanks for your interest in EBANA. There has been a lot of updates made to the code base since the last time I pushed the updates to github. Updates such as optimizing the simulation time, use of memristors, features such as callback, transient simulation, etc. However, the code is not really in a good state to push online, which is why I haven't made those changes yet. For now, I'm going to accept your fixes, but will make sure to try to clean up the code to push it as soon as possible.
